### PR TITLE
Touchscreen Dev

### PR DESCRIPTION
**Pull request by bridgesense**
The stock keyboard is pretty useless.  No need for it to come up every time the app opens.

### CODE REVIEW

**Comment by bridgesense** [comment]
In landscape mode, it pulls in the click and emulation viewports dynamically to generate the results.  The portrait view is a bit more tricky, but I see that hard coded in other areas as well.  I'm a PHP guy myself with not a lot of working knowledge of C, so there's some beautification that needs done -- as I opted for the easier route of using a global variable.

Since the legacy mouse is still available through click and drag, I was thinking of binding the double click event to the legacy click submission.  Otherwise, it may just be best to add a new option to switch between modes.

I included a video presentation.

[Visual Example on Youtube](https://www.youtube.com/watch?vcswHzw9H_T_4)

**Comment by Dimillian** [comment]
Trying on Daggerfall on iPhone 7. I guess it depend of the resolution of the game right ? I might have to do a sort of conversation from the iPhone native resolution to the game 800X600 ?

**Comment by bridgesense** [comment]
As Litchie mentioned there is a lot of testing todo.  Games released in 95+ use different emulation process and have not been tested.  There is no click and drag functionality either yet either.  So there is a quite a bit left to do.

There are two resolutions to consider.  There is the click field resolution and the emulated resoultion that the click coordinate needs converted to.  The x, y, and xrel and yrel coordinates of the SDL button and motion events do not appear to be valid coordinates in either resolution.

**Comment by bridgesense** [comment]
c

**Comment by bridgesense** [comment]
So this was a bit more complicated.  Adding a temporary fix to allow manual adjustment of the click field.  Now you can manually line up the cursor.  For instance, these are sample settings for Gloriana.

**Comment by litchie** [comment]
@bridgesense Interesting development. I think eventually we can have different direction touch configuration for different games. 

> For some games there appears to be some calculation that is doubling the width of the click field, but the height remains the same.

It would be great if you can specify which games. 

Anyway, keep up what you are doing. It's really great.

**Comment by bridgesense** [comment]
Here are some of the settings so far that I've discovered.  They appear to work regardless whether using an iPhone or iPad.

Custom Values Disabled (or Enabled with 1x width, 1x height):
The Patrician
Zeppelin

Custom Values Enabled with 2x width, 1x height:
1830 Railroads and Robber Barons
Master of Orion 2

Custom Values Enabled with 4x width, 4x height:
Gloriana

**Comment by Dimillian** [comment]
Awesome progress! 

But I've tested it on Daggerfall, the mouse is below the screen with every possible settings :/

**Comment by bridgesense** [comment]
Thanks for your input.  Gloriana is an interesting test subject too because there are two different video modes.  There is the predominant mode that works with the 4x, 4x.  Then there is the city scape which is a panorama of three 640x480 backdrops that work with a setting of 6x width and 4x height.  It doesn't matter which color mode is selected or the size of the device being used.  The cursor lands in the same relative position.

Even though I am not latching onto the appropriately skewed width and height to convert the point properly, the game resolution seems to be skewed cleanly in multiples of 2 with the figures I am using.  The figures seem to be the same no mater what the device resolution is.

... clicking on the same spot on the screen:
Here is an example of a working intro screen for Gloriana on the iPhone (1334 x 750):
(640(?)  x 4) / 667 (Click Field Max X)  * 504 (Click Field Touch Coord X) = 2560 (Mouse_CursorSet X)
(480(?)  x 4) / 375 (Click Field Max Y)  * 91 (Click Field Touch Coord Y) = 1920 (Mouse CursorSet Y)

Here is an example of a working intro screen for Gloriana on the iPad Air 2 (2048 x 1536):
(640(?)  x 4) / 1024 (Click Field Max X)  * 774 (Click Field Touch Coord X) = 2560 (Mouse_CursorSet X)
(480(?)  x 4) / 768 (Click Field Max Y)  * 190 (Click Field Touch Coord Y) = 1920 (Mouse CursorSet Y)

For Gloriana mouse.cpp in dosbox has calculated a whopping click field of 2560 x 1920 no matter what device is being used.  Once I tear apart the math in DrawCursor, we should be able to replace the (640(?) x 4) with a proper calculation.  After that, click and drag won't be an issue to implement either.

**Comment by bridgesense** [comment]
Default mode is quite a bit more robust.  Unfortunately, the custom settings may end up being a permanent feature.

**Comment by Dimillian** [comment]
Any progress on how we can handle the top of the screen? Need that toppar but also need to not trigger when touching here. Maybe a small toggle at the bottom of the screen. Like the one to switch between joystick and arrow keys.

**Comment by bridgesense** [comment]
That's a thought.  Might be a quicker solution.  Out of town this week, but I'll review putting a button there to extend the bar.  I was thinking of also adding the joystick and keyboard toggles to the screen as well.  It would make things a lot easier.

**Comment by smith-chris** [comment]
Hi bridgesense,

it looks awesome on the video! I tried to run it on my local machine though and it throws errors at me :( I tried **master** and **capitalism_plus_gog** branches and the latter one says:

`ld: warning: ignoring file /Users/krzysiek/Library/Developer/Xcode/DerivedData/dospad-bpufwotiyzembgfcpwfwhvdlpkbf/Build/Products/Debug-iphonesimulator/libdosbox.a, file was built for archive which is not the architecture being linked (i386): /Users/krzysiek/Library/Developer/Xcode/DerivedData/dospad-bpufwotiyzembgfcpwfwhvdlpkbf/Build/Products/Debug-iphonesimulator/libdosbox.a
ld: warning: ignoring file /Users/krzysiek/Library/Developer/Xcode/DerivedData/dospad-bpufwotiyzembgfcpwfwhvdlpkbf/Build/Products/Debug-iphonesimulator/libminizip.a, file was built for archive which is not the architecture being linked (i386): /Users/krzysiek/Library/Developer/Xcode/DerivedData/dospad-bpufwotiyzembgfcpwfwhvdlpkbf/Build/Products/Debug-iphonesimulator/libminizip.a
ld: warning: ignoring file /Users/krzysiek/Library/Developer/Xcode/DerivedData/dospad-bpufwotiyzembgfcpwfwhvdlpkbf/Build/Products/Debug-iphonesimulator/libSDL_net.a, file was built for archive which is not the architecture being linked (i386): /Users/krzysiek/Library/Developer/Xcode/DerivedData/dospad-bpufwotiyzembgfcpwfwhvdlpkbf/Build/Products/Debug-iphonesimulator/libSDL_net.a
Undefined symbols for architecture i386:
  "_unzGoToFirstFile", referenced from:
      -[ZipArchive UnzipFileTo:overWrite:] in ZipArchive.o
  "_unzOpenCurrentFile", referenced from:
      -[ZipArchive UnzipFileTo:overWrite:] in ZipArchive.o
  "_unzOpen", referenced from:
      -[ZipArchive UnzipOpenFile:] in ZipArchive.o
  "_unzClose", referenced from:
      -[ZipArchive UnzipCloseFile] in ZipArchive.o
  "_automount_path", referenced from:
      _main in main.o
  "_unzCloseCurrentFile", referenced from:
      -[ZipArchive UnzipFileTo:overWrite:] in ZipArchive.o
  "_zipClose", referenced from:
      -[ZipArchive CloseZipFile2] in ZipArchive.o
  "_zipCloseFileInZip", referenced from:
      -[ZipArchive addFileToZip:newname:] in ZipArchive.o
  "_unzGetGlobalInfo", referenced from:
      -[ZipArchive UnzipOpenFile:] in ZipArchive.o
  "_unzReadCurrentFile", referenced from:
      -[ZipArchive UnzipFileTo:overWrite:] in ZipArchive.o
  "_zipOpenNewFileInZip", referenced from:
      -[ZipArchive addFileToZip:newname:] in ZipArchive.o
  "_zipOpen", referenced from:
      -[ZipArchive CreateZipFile2:] in ZipArchive.o
  "_unzGetCurrentFileInfo", referenced from:
      -[ZipArchive UnzipFileTo:overWrite:] in ZipArchive.o
  "_zipWriteInFileInZip", referenced from:
      -[ZipArchive addFileToZip:newname:] in ZipArchive.o
  "_unzGoToNextFile", referenced from:
      -[ZipArchive UnzipFileTo:overWrite:] in ZipArchive.o
  "_SDL_main", referenced from:
      -[SDLUIKitDelegate postFinishLaunch] in SDL_uikitappdelegate.o
      -[DosEmuThread run] in DosEmuThread.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Xcode version: 9.2, iphone 7 simulator

Are there any additional steps to get it running other than just clone the repo?

Cheers,
Chris

**Review by saowaluck2531 — APPROVED** [review]

**Comment by DanEEStar** [comment]
@litchie @bridgesense I want to vouch for these changes!

I added the touch-changes to a current copy of the master branch and it works great!

The "default" setting of 1x width, 1x height with direct touch worked for many games I tested them with, like:

* X-COM UFO Defense
* Warcraft 1
* Fantasy General
* Lemmings 2
* Master of Orion 1
* Pizza Connection

Especially a game like Fantasy General almost works like a "native" app with the direct touch settings!

Only Lemmings 1 seemed to require a different setting of width 2x

I cherry-picked (manually copied) the touch code. I did not test the keyboard or other changes...

**Comment by litchie** [comment]
@DanEEStar Thank you for testing. Will look into it when UI refactoring is done.

**Comment by litchie** [comment]
See #110

**Pull request closed without merging**
