### PR TITLE
Support remapping the thumbstick buttons

### PR DESCRIPTION
**Pull request by yoshisuga**
IMG_29934BC4DFD9-1 2

Small change to support the thumbstick buttons on controllers like the PS4, Xbox One and other compatible controllers (tried the 8bitdo SN30 Pro).

### CODE REVIEW

**Comment by litchie** [comment]
@yoshisuga Thank you for your work. I would love to include your changes, but I want to try to use one of those thumbsticks for emulating mouse (the other is already used for joystick), just like the ThinkPad red dot, and press on the button will be treated as mouse left click.

**Comment by litchie** [comment]
Of couse you can do it if you find the mouse feature interesting enough.

**Comment by yoshisuga** [comment]
Ah! I see, ok. I think that sounds interesting but I'm a little unsure how it'd work in practice. 

Clicking and dragging, for example, by holding the thumb stick button down and moving might feel a little awkward to do. I guess we'd need to implement it to see how it'd feel (and it doesn't sound like it'd be too hard to do)

Feel free to close this if you think it's not within the scope you were thinking - thanks!

**Comment by litchie** [comment]
Or we can make joystick & mouse mode exclusive, so that you can move the mouse with either stick, so dragging may be easier.

**Comment by litchie** [comment]
Closing because those buttons are reserved for mouse emulation.

**Pull request closed without merging**
