### PR TITLE
Replace dosbox with SVN DAUM version

### PR DESCRIPTION
**Pull request by imxieyi**
Compared to original DOSBOX, [DOSBox SVN Daum](http://ykhwong.x-y.net/) is much more powerful and provides a lot of more advanced features such as [386 real mode](https://en.wikipedia.org/wiki/Real_mode), which is required by some applications and games. It can even boot [muLinux](http://micheleandreoli.org/public/Software/mulinux/):
image
image

**However the porting is not finished.** ~A known issue is that guest OSes booting from .img files, e.g. Windows 95, run extremely slow.~(Seems to have been fixed by changing config) But running directly from file system, e.g. Windows 3.1, is as fast as usual.

### CODE REVIEW

**Comment by DominusExult** [comment]
I would err on the cautious side. Daum has been broken for a while now, and the incomplete code it has borrowed by dosbox-x can be a burden, too

**Comment by litchie** [comment]
@DominusExult Thank you for the heads-up!

**Comment by imxieyi** [comment]
@DominusExult I agree with you. Further tests are required to ensure its stability. Currently I haven't seen any defeats compared to the original version. I'd like to know which part is "broken". Maybe I can try to fix them?

**Comment by DominusExult** [comment]
The whole ide thing of adding drives for emulation of Windows 95 is based on three or four years old WIP of Dosbox-x which got much more improvements since then.
Also there were reports of some graphics modes broken in Daum‘s last version (on Vogons form, I‘d need to look).
The experimental savestate feature is only half working and saw some improvement in another patch since then.
Overall Daum adds too many things that no one really tested if they work well together.
@litchie you will need to decide what direction you want to go: playing Dos games or being able to boot other operating systems.
For Dos games, I‘d stay with vanilla Dosbox instead of ggoing untested routes.

**Comment by litchie** [comment]
@DominusExult As the project name suggests, dospad is only about DOS games.

@imxieyi  If you have some commits about UI improvements, I'll be happy to check. However, using an experimental dosbox kernel on the master branch is not an option. Especially when we still have crash-on-rotation bug on iPhone, we can't afford to add more issues to the mix.

**Comment by imxieyi** [comment]
Okay. I understand.
I will keep it my own repository.
Maybe you can add a link to my fork for those who want to run Windows 9x on iOS devices.

**Pull request closed without merging**
